### ISSUE TITLE
Missing Symbols category

### ISSUE THREAD

**Issue by ManuelOrtega** [SabatinoMasala/EmojiFiesta#1]
Hi @SabatinoMasala,

First of all, congratulations for this amazing helper. It's been a lot of help indeed!

However, seems that the Symbols category is not returning any emoji. I mean all the emojis from this category: 

http://emojipedia.org/symbols/

Do you have any idea about what this is happening? I'm trying to identify the reason with no success.

Thank you very much in advance.

Manuel

**Comment by SabatinoMasala** [comment]
In iOS 10.3 the [UIKeyboardEmojiCategory class](https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/UIKit.framework/UIKeyboardEmojiCategory.h) has changed, so this demo would probably crash. I'll try to make another demo for iOS 11 soon.

**Comment by Nosskirneh** [comment]
Fixed in https://github.com/SabatinoMasala/EmojiFiesta/pull/2.

**Comment by SabatinoMasala** [comment]
Just merged #2, closing this issue.
